name: Lambda Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps & zip
        run: |
          pip install -r requirements.txt -t package
          cp lambda_function.py package/
          cd package && zip -r ../function.zip .

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name MyLambdaFunction \
            --zip-file fileb://function.zip \
            --publish
